# User Based Recommendation System

### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
r_cols = ['user_id','movie_id','rating','unix_timestamp']
ratings = pd.read_csv('C:\Priya learning path\Hope_Artifiacial_Intelligence\Recommendation system\Collabrative Recommendation System\ml-100k/u.data',
                      sep='\t', names=r_cols, encoding='latin-1')

In [3]:
ratings.head()

   user_id  movie_id  rating  unix_timestamp
0      196       242       3       881250949
1      186       302       3       891717742
2       22       377       1       878887116
3      244        51       2       880606923
4      166       346       1       886397596

### Unique values of users & items(movies)

In [4]:
n_users = ratings.user_id.unique().shape[0]
n_items = ratings.movie_id.unique().shape[0]

In [5]:
print(f'No of users : {n_users}')
print(f'No of items : {n_items}')

No of users : 943
No of items : 1682

## Step 1 -  Create pivot table for users and movies based on rating

In [6]:
data_mat = ratings.pivot_table(index='user_id', columns='movie_id',values='rating')

In [7]:
data_mat.head()

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###  Replace all the NaN values to 0

In [8]:
data_matrix = data_mat.replace(np.nan,0)

In [9]:
data_matrix.head()

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Step 2 - Finding Cosine Similarity between users and items

In [10]:
from sklearn.metrics.pairwise import pairwise_distances

user_similarity = pairwise_distances(data_matrix, metric='cosine')
item_similarity = pairwise_distances(data_matrix.T, metric='cosine')

In [11]:
user_similarity

array([[2.44249065e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 3.33066907e-16, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 1.11022302e-16, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

In [12]:
user_similarity.shape

(943, 943)

In [13]:
user_similarity

array([[2.44249065e-15, 8.33069016e-01, 9.52540457e-01, ...,
        8.51383057e-01, 8.20492117e-01, 6.01825261e-01],
       [8.33069016e-01, 3.33066907e-16, 8.89408675e-01, ...,
        8.38515222e-01, 8.27732187e-01, 8.94202122e-01],
       [9.52540457e-01, 8.89408675e-01, 0.00000000e+00, ...,
        8.98757435e-01, 8.66583851e-01, 9.73444131e-01],
       ...,
       [8.51383057e-01, 8.38515222e-01, 8.98757435e-01, ...,
        0.00000000e+00, 8.98358201e-01, 9.04880419e-01],
       [8.20492117e-01, 8.27732187e-01, 8.66583851e-01, ...,
        8.98358201e-01, 1.11022302e-16, 8.17535338e-01],
       [6.01825261e-01, 8.94202122e-01, 9.73444131e-01, ...,
        9.04880419e-01, 8.17535338e-01, 0.00000000e+00]])

## Step 3 - Predict the non filled rating for the users using formula (Helps to find the unwatched movies)
### Using formula for user and item we are calcuating the score value

In [14]:
def predict(ratings, similarity, type='user'):
    if type == 'user':
        # Step 1: Calculate the mean rating for each user
        mean_user_rating = ratings.mean(axis=1)
        # Step 2: Subtract the mean rating from each user's ratings to normalize
        ratings_diff = (ratings - np.array(mean_user_rating)[:, np.newaxis])  # Fix here
        # Step 3: Compute the predicted ratings
        pred = np.array(mean_user_rating)[:, np.newaxis] + similarity.dot(ratings_diff) / np.array([np.abs(similarity).sum(axis=1)]).T
    elif type == 'item':
        # Step 1: Compute the predicted ratings by multiplying ratings with similarity matrix
        pred = ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [15]:
user_prediction = predict(data_matrix, user_similarity, type='user')
user_prediction

array([[ 2.06532606,  0.73430275,  0.62992381, ...,  0.39359041,
         0.39304874,  0.3927712 ],
       [ 1.76308836,  0.38404019,  0.19617889, ..., -0.08837789,
        -0.0869183 , -0.08671183],
       [ 1.79590398,  0.32904733,  0.15882885, ..., -0.13699223,
        -0.13496852, -0.13476488],
       ...,
       [ 1.59151513,  0.27526889,  0.10219534, ..., -0.16735162,
        -0.16657451, -0.16641377],
       [ 1.81036267,  0.40479877,  0.27545013, ..., -0.00907358,
        -0.00846587, -0.00804858],
       [ 1.8384313 ,  0.47964837,  0.38496292, ...,  0.14686675,
         0.14629808,  0.14641455]])

#### Step by step explaination just for understanding

In [16]:
mean_user_rating = data_matrix.mean(axis=1)
mean_user_rating

user_id
1      0.583829
2      0.136742
3      0.089774
4      0.061831
5      0.299049
         ...
939    0.124257
940    0.219976
941    0.052913
942    0.200357
943    0.340666
Length: 943, dtype: float64

In [17]:
ratings_diff = (data_matrix - np.array(mean_user_rating)[:, np.newaxis])
ratings_diff

movie_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,4.416171,2.416171,3.416171,2.416171,2.416171,4.416171,3.416171,0.416171,4.416171,2.416171,...,-0.583829,-0.583829,-0.583829,-0.583829,-0.583829,-0.583829,-0.583829,-0.583829,-0.583829,-0.583829
2,3.863258,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,1.863258,...,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742,-0.136742
3,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,...,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774,-0.089774
4,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,...,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831,-0.061831
5,3.700951,2.700951,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,...,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049,-0.299049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,4.875743,-0.124257,...,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257,-0.124257
940,-0.219976,-0.219976,-0.219976,1.780024,-0.219976,-0.219976,3.780024,4.780024,2.780024,-0.219976,...,-0.219976,-0.219976,-0.219976,-0.219976,-0.219976,-0.219976,-0.219976,-0.219976,-0.219976,-0.219976
941,4.947087,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913,3.947087,-0.052913,-0.052913,-0.052913,...,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913,-0.052913
942,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,...,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357,-0.200357
943,-0.340666,4.659334,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,2.659334,-0.340666,...,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666,-0.340666

In [18]:
user_similarity.dot(ratings_diff)

array([[1053.46456048,  106.99918332,   32.77730441, ..., -135.27488255,
        -135.66005564, -135.85741105],
       [1236.14249108,  187.96477188,   45.1764139 , ..., -171.10760287,
        -169.99820267, -169.8412708 ],
       [1409.18485925,  197.62870362,   57.03606449, ..., -187.29854641,
        -185.62705133, -185.45885449],
       ...,
       [1245.81782545,  180.04311388,   39.90412677, ..., -178.35011786,
        -177.72089084, -177.5907325 ],
       [1258.24647345,  159.77486735,   58.68675582, ..., -163.6732682 ,
        -163.19833111, -162.87221498],
       [1128.30290113,  104.69887603,   33.37003481, ..., -145.99356249,
        -146.42195908, -146.33422024]])

#### Just an Example for understanding dot product

user_similarity = np.array([
    [1.0, 0.8],
    [0.8, 1.0]
])

ratings_diff = np.array([
    [5, 4],
    [3, 2]
])

#### Perform dot product
result = user_similarity.dot(ratings_diff)
print(result)

[
    [1.0*5 + 0.8*3, 1.0*4 + 0.8*2],
    [0.8*5 + 1.0*3, 0.8*4 + 1.0*2]
]

np.array([np.abs(similarity).sum(axis=1)]).T

####  Example
row_sums = np.array([1.3, 1.2])  # Shape (2,)
row_sums_T = row_sums.T          # Shape (2, 1)
print(row_sums_T)
#### Output:
[[1.3]
 [1.2]]

## Step 4 - Select the User Input

### As per User based filtering ,first have to find similarity between the input user and others

In [19]:
user_input = 34

In [20]:
### Convert the user_simi table into dataframe

user_sim_table = pd.DataFrame(user_similarity)
user_sim_table

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.442491e-15,8.330690e-01,0.952540,0.935642,0.621525,0.569761,0.559633,0.680928,0.921862,0.623456,...,0.630473,0.880518,0.725124,0.810295,0.802674,0.881905,6.859280e-01,0.851383,8.204921e-01,0.601825
1,8.330690e-01,3.330669e-16,0.889409,0.821879,0.927021,0.754157,0.892672,0.896656,0.838952,0.840138,...,0.843014,0.692058,0.641211,0.575954,0.680111,0.771417,7.732100e-01,0.838515,8.277322e-01,0.894202
2,9.525405e-01,8.894087e-01,0.000000,0.655849,0.978755,0.927585,0.933863,0.916940,0.938960,0.934849,...,0.968125,0.957247,0.836171,0.930962,0.875755,0.973729,8.381099e-01,0.898757,8.665839e-01,0.973444
3,9.356422e-01,8.218788e-01,0.655849,0.000000,0.968196,0.931956,0.908770,0.811940,0.898716,0.939141,...,0.947893,0.963216,0.866885,0.806529,0.853942,0.969862,8.031418e-01,0.847959,8.299139e-01,0.941248
4,6.215248e-01,9.270210e-01,0.978755,0.968196,0.000000,0.762714,0.626400,0.751070,0.943153,0.798573,...,0.661206,0.919420,0.905076,0.920221,0.851393,0.928541,7.600453e-01,0.860405,8.475026e-01,0.686059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,8.819047e-01,7.714166e-01,0.973729,0.969862,0.928541,0.888148,0.892973,0.904102,0.960148,0.928540,...,0.933961,0.568846,0.741979,0.773551,0.567334,0.000000,9.123129e-01,0.819971,9.567357e-01,0.855750
939,6.859280e-01,7.732100e-01,0.838110,0.803142,0.760045,0.647551,0.670075,0.753117,0.879505,0.657039,...,0.672847,0.892976,0.812464,0.818683,0.824842,0.912313,3.330669e-16,0.854848,7.386238e-01,0.758972
940,8.513831e-01,8.385152e-01,0.898757,0.847959,0.860405,0.855554,0.940007,0.853855,0.856755,0.909695,...,0.953048,0.796699,0.711682,0.765789,0.686600,0.819971,8.548477e-01,0.000000,8.983582e-01,0.904880
941,8.204921e-01,8.277322e-01,0.866584,0.829914,0.847503,0.682672,0.717997,0.824678,0.907503,0.787670,...,0.773560,0.926487,0.910412,0.870446,0.900615,0.956736,7.386238e-01,0.898358,1.110223e-16,0.817535
942,6.018253e-01,8.942021e-01,0.973444,0.941248,0.686059,0.723958,0.605636,0.700191,0.924383,0.778140,...,0.736209,0.789237,0.856747,0.922207,0.797756,0.855750,7.589723e-01,0.904880,8.175353e-01,0.000000




### Step 8 - Filter the movie_id from similar users which is not present in user input
### Step 9 - Filtered movie_id has to be checked with the Prediction Table because filtered movies are the recommended movie list for user input.

## Step 5 -  Find the similar users for 34 using the 'cosine table' of the highest rated

In [21]:
similar_user_input= user_sim_table[user_input].sort_values(ascending=True).head(5).index
similar_user_input

Index([34, 450, 852, 811, 509], dtype='int64')

### Convert into List

In [22]:
similar_user_input = list(similar_user_input)
similar_user_input

[34, 450, 852, 811, 509]

## Step 6 - Similar Users watched movie list
### Using similar_user_input, can select movie id from ratings table

In [23]:
similar_user_movieid_list = []
for sim_user in similar_user_input:
    sim_movies = list(ratings[ratings['user_id']==sim_user]['movie_id'])
    similar_user_movieid_list.append(sim_movies)

In [24]:
similar_user_movieid_list

[[312,
  242,
  690,
  310,
  259,
  299,
  245,
  332,
  329,
  286,
  1024,
  324,
  294,
  292,
  990,
  289,
  898,
  899,
  288,
  991],
 [470,
  783,
  1147,
  100,
  58,
  142,
  801,
  216,
  785,
  162,
  144,
  462,
  384,
  739,
  1269,
  179,
  38,
  659,
  252,
  1160,
  566,
  496,
  679,
  387,
  908,
  265,
  1226,
  183,
  1037,
  194,
  902,
  1263,
  64,
  1036,
  942,
  467,
  1212,
  97,
  762,
  143,
  583,
  480,
  846,
  561,
  487,
  2,
  237,
  39,
  778,
  815,
  708,
  400,
  495,
  382,
  518,
  110,
  1203,
  710,
  660,
  152,
  304,
  520,
  604,
  642,
  494,
  211,
  847,
  559,
  1446,
  204,
  904,
  1092,
  281,
  526,
  139,
  200,
  367,
  553,
  523,
  685,
  478,
  177,
  742,
  1044,
  509,
  89,
  238,
  29,
  15,
  837,
  65,
  49,
  176,
  434,
  729,
  1184,
  70,
  728,
  174,
  1047,
  723,
  477,
  419,
  689,
  582,
  270,
  7,
  155,
  12,
  774,
  383,
  488,
  145,
  401,
  301,
  468,
  157,
  771,
  650,
  288,
  95,
  1,
  154,
  1020,
  712,
  227,
  923,
  1222,
  1152,
  101,
  395,
  1050,
  94,
  272,
  629,
  225,
  402,
  736,
  707,
  60,
  613,
  465,
  747,
  493,
  123,
  10,
  514,
  1041,
  13,
  451,
  418,
  611,
  258,
  905,
  1479,
  502,
  792,
  131,
  673,
  56,
  940,
  1192,
  158,
  203,
  193,
  612,
  1054,
  134,
  99,
  607,
  127,
  428,
  378,
  294,
  469,
  208,
  290,
  1030,
  632,
  663,
  878,
  132,
  751,
  1039,
  967,
  1603,
  472,
  474,
  765,
  482,
  1261,
  614,
  700,
  92,
  928,
  589,
  591,
  385,
  282,
  305,
  275,
  873,
  195,
  299,
  153,
  381,
  231,
  865,
  484,
  1033,
  199,
  311,
  433,
  1140,
  315,
  790,
  371,
  357,
  1172,
  1401,
  354,
  54,
  558,
  241,
  1402,
  207,
  550,
  637,
  414,
  340,
  506,
  313,
  1221,
  283,
  692,
  80,
  66,
  222,
  647,
  192,
  549,
  136,
  610,
  35,
  507,
  490,
  510,
  164,
  135,
  735,
  245,
  842,
  714,
  4,
  302,
  121,
  430,
  1425,
  686,
  775,
  312,
  205,
  81,
  1286,
  525,
  77,
  921,
  1048,
  965,
  26,
  651,
  934,
  1444,
  71,
  98,
  233,
  141,
  956,
  491,
  185,
  448,
  169,
  1441,
  1153,
  328,
  421,
  182,
  163,
  83,
  187,
  661,
  471,
  239,
  497,
  264,
  966,
  527,
  731,
  823,
  274,
  380,
  316,
  166,
  125,
  535,
  1208,
  393,
  845,
  609,
  1091,
  1220,
  1271,
  79,
  1116,
  278,
  969,
  277,
  1248,
  191,
  455,
  197,
  86,
  432,
  287,
  807,
  51,
  606,
  1435,
  761,
  67,
  479,
  705,
  821,
  622,
  90,
  709,
  500,
  396,
  202,
  530,
  427,
  481,
  936,
  73,
  1028,
  112,
  503,
  716,
  82,
  126,
  373,
  280,
  292,
  422,
  869,
  476,
  443,
  832,
  226,
  939,
  608,
  631,
  167,
  693,
  431,
  1521,
  602,
  1053,
  648,
  715,
  215,
  900,
  254,
  210,
  657,
  88,
  117,
  655,
  269,
  180,
  1163,
  794,
  951,
  568,
  28,
  633,
  87,
  1282,
  168,
  630,
  1303,
  332,
  3,
  717,
  557,
  218,
  223,
  499,
  173,
  161,
  1119,
  229,
  704,
  416,
  417,
  483,
  505,
  528,
  570,
  1115,
  196,
  133,
  620,
  310,
  618,
  300,
  114,
  511,
  435,
  748,
  727,
  926,
  1284,
  749,
  284,
  318,
  968,
  501,
  307,
  713,
  188,
  662,
  96,
  389,
  50,
  347,
  230,
  372,
  181,
  627,
  336,
  235,
  190,
  102,
  403,
  221,
  23,
  734,
  671,
  43,
  172,
  345,
  741,
  118,
  386,
  776,
  519,
  866,
  33,
  702,
  1135,
  485,
  273,
  76,
  492,
  750,
  1311,
  1249,
  1107,
  260,
  1197,
  588,
  546,
  392,
  78,
  597,
  213,
  489,
  619,
  214,
  696,
  220,
  812,
  571,
  1297,
  725,
  322,
  111,
  286,
  724,
  457,
  259,
  44,
  722,
  47,
  616,
  91,
  699,
  601,
  186,
  603,
  61,
  11,
  423,
  781,
  521,
  498,
  140,
  151,
  756,
  1112,
  59,
  69,
  366,
  1518,
  405,
  415,
  232,
  504,
  63,
  795,
  628,
  22,
  356,
  1421,
  25,
  228,
  170,
  1126,
  516,
  1480,
  1061,
  234,
  399,
  178,
  584,
  732,
  388,
  1490,
  654],
 [685,
  473,
  408,
  323,
  118,
  257,
  151,
  546,
  127,
  597,
  289,
  820,
  930,
  678,
  841,
  515,
  181,
  7,
  405,
  260,
  840,
  50,
  681,
  274,
  1052,
  825,
  969,
  259,
  25,
  235,
  1,
  122,
  827,
  252,
  358,
  472,
  117,
  826,
  121,
  264,
  109,
  1615,
  407,
  568,
  100,
  506,
  250,
  926,
  290],
 [301,
  292,
  304,
  294,
  748,
  690,
  258,
  323,
  892,
  289,
  307,
  286,
  315,
  300,
  308,
  895,
  988,
  321,
  678,
  243,
  901],
 [319,
  50,
  288,
  680,
  751,
  310,
  300,
  260,
  879,
  687,
  258,
  603,
  332,
  302,
  754,
  289,
  301,
  345,
  326,
  307,
  343,
  268,
  892,
  338,
  266,
  328,
  690,
  245,
  181,
  309,
  294,
  271,
  705]]

In [25]:
len(similar_user_movieid_list)

5

### Convert all the movie list as single

In [26]:
import itertools
similar_user_movieid_single_list = list(itertools.chain.from_iterable(similar_user_movieid_list))
len(similar_user_movieid_single_list)

663

### Unique movie_id from the list

In [27]:
unique_movieid_similar_user = set(similar_user_movieid_single_list)
len(unique_movieid_similar_user)

590

## Step 7 - User input watched movie list

In [28]:
user_input_watched_movie_list = list(ratings[ratings['user_id']==user_input]['movie_id'].values)
len(user_input_watched_movie_list)

20

In [29]:
user_input_watched_movie_list

[312,
 242,
 690,
 310,
 259,
 299,
 245,
 332,
 329,
 286,
 1024,
 324,
 294,
 292,
 990,
 289,
 898,
 899,
 288,
 991]

## Step 9 - Create a list that should have recommended movie id to the user input

In [30]:
recommended_movie_list = []
for per_id in unique_movieid_similar_user:
    if per_id in user_input_watched_movie_list:
        pass
    else:
        recommended_movie_list.append(per_id)

In [31]:
len(recommended_movie_list)

570

In [32]:
# Cross Checking
sorted(recommended_movie_list)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 243,
 250,
 252,
 254,
 257,
 258,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 280,
 281,
 282,
 283,
 284,
 287,
 290,
 300,
 301,
 302,
 304,
 305,
 307,
 308,
 309,
 311,
 313,
 315,
 316,
 318,
 319,
 321,
 322,
 323,
 326,
 328,
 336,
 338,
 340,
 343,
 345,
 347,
 354,
 356,
 357,
 358,
 366,
 367,
 371,
 372,
 373,
 378,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 392,
 393,
 395,
 396,
 399,
 400,
 401,
 402,
 403,
 405,
 407,
 408,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 427,
 428,
 430,
 431,
 432,
 433,
 434,
 435,
 443,
 448,
 451,
 455,
 457,
 462,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 514,
 515,
 516,
 518,
 519,
 520,
 521,
 523,
 525,
 526,
 527,
 528,
 530,
 535,
 546,
 549,
 550,
 553,
 557,
 558,
 559,
 561,
 566,
 568,
 570,
 571,
 582,
 583,
 584,
 588,
 589,
 591,
 597,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 616,
 618,
 619,
 620,
 622,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 637,
 642,
 647,
 648,
 650,
 651,
 654,
 655,
 657,
 659,
 660,
 661,
 662,
 663,
 671,
 673,
 678,
 679,
 680,
 681,
 685,
 686,
 687,
 689,
 692,
 693,
 696,
 699,
 700,
 702,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 722,
 723,
 724,
 725,
 727,
 728,
 729,
 731,
 732,
 734,
 735,
 736,
 739,
 741,
 742,
 747,
 748,
 749,
 750,
 751,
 754,
 756,
 761,
 762,
 765,
 771,
 774,
 775,
 776,
 778,
 781,
 783,
 785,
 790,
 792,
 794,
 795,
 801,
 807,
 812,
 815,
 820,
 821,
 823,
 825,
 826,
 827,
 832,
 837,
 840,
 841,
 842,
 845,
 846,
 847,
 865,
 866,
 869,
 873,
 878,
 879,
 892,
 895,
 900,
 901,
 902,
 904,
 905,
 908,
 921,
 923,
 926,
 928,
 930,
 934,
 936,
 939,
 940,
 942,
 951,
 956,
 965,
 966,
 967,
 968,
 969,
 988,
 1020,
 1028,
 1030,
 1033,
 1036,
 1037,
 1039,
 1041,
 1044,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1061,
 1091,
 1092,
 1107,
 1112,
 1115,
 1116,
 1119,
 1126,
 1135,
 1140,
 1147,
 1152,
 1153,
 1160,
 1163,
 1172,
 1184,
 1192,
 1197,
 1203,
 1208,
 1212,
 1220,
 1221,
 1222,
 1226,
 1248,
 1249,
 1261,
 1263,
 1269,
 1271,
 1282,
 1284,
 1286,
 1297,
 1303,
 1311,
 1401,
 1402,
 1421,
 1425,
 1435,
 1441,
 1444,
 1446,
 1479,
 1480,
 1490,
 1518,
 1521,
 1603,
 1615]

In [33]:
# Cross Checking
sorted(unique_movieid_similar_user)

[1,
 2,
 3,
 4,
 7,
 10,
 11,
 12,
 13,
 15,
 22,
 23,
 25,
 26,
 28,
 29,
 33,
 35,
 38,
 39,
 43,
 44,
 47,
 49,
 50,
 51,
 54,
 56,
 58,
 59,
 60,
 61,
 63,
 64,
 65,
 66,
 67,
 69,
 70,
 71,
 73,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 109,
 110,
 111,
 112,
 114,
 117,
 118,
 121,
 122,
 123,
 125,
 126,
 127,
 131,
 132,
 133,
 134,
 135,
 136,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 151,
 152,
 153,
 154,
 155,
 157,
 158,
 161,
 162,
 163,
 164,
 166,
 167,
 168,
 169,
 170,
 172,
 173,
 174,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 185,
 186,
 187,
 188,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 199,
 200,
 202,
 203,
 204,
 205,
 207,
 208,
 210,
 211,
 213,
 214,
 215,
 216,
 218,
 220,
 221,
 222,
 223,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 237,
 238,
 239,
 241,
 242,
 243,
 245,
 250,
 252,
 254,
 257,
 258,
 259,
 260,
 264,
 265,
 266,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 277,
 278,
 280,
 281,
 282,
 283,
 284,
 286,
 287,
 288,
 289,
 290,
 292,
 294,
 299,
 300,
 301,
 302,
 304,
 305,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 315,
 316,
 318,
 319,
 321,
 322,
 323,
 324,
 326,
 328,
 329,
 332,
 336,
 338,
 340,
 343,
 345,
 347,
 354,
 356,
 357,
 358,
 366,
 367,
 371,
 372,
 373,
 378,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 392,
 393,
 395,
 396,
 399,
 400,
 401,
 402,
 403,
 405,
 407,
 408,
 414,
 415,
 416,
 417,
 418,
 419,
 421,
 422,
 423,
 427,
 428,
 430,
 431,
 432,
 433,
 434,
 435,
 443,
 448,
 451,
 455,
 457,
 462,
 465,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 509,
 510,
 511,
 514,
 515,
 516,
 518,
 519,
 520,
 521,
 523,
 525,
 526,
 527,
 528,
 530,
 535,
 546,
 549,
 550,
 553,
 557,
 558,
 559,
 561,
 566,
 568,
 570,
 571,
 582,
 583,
 584,
 588,
 589,
 591,
 597,
 601,
 602,
 603,
 604,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 616,
 618,
 619,
 620,
 622,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 637,
 642,
 647,
 648,
 650,
 651,
 654,
 655,
 657,
 659,
 660,
 661,
 662,
 663,
 671,
 673,
 678,
 679,
 680,
 681,
 685,
 686,
 687,
 689,
 690,
 692,
 693,
 696,
 699,
 700,
 702,
 704,
 705,
 707,
 708,
 709,
 710,
 712,
 713,
 714,
 715,
 716,
 717,
 722,
 723,
 724,
 725,
 727,
 728,
 729,
 731,
 732,
 734,
 735,
 736,
 739,
 741,
 742,
 747,
 748,
 749,
 750,
 751,
 754,
 756,
 761,
 762,
 765,
 771,
 774,
 775,
 776,
 778,
 781,
 783,
 785,
 790,
 792,
 794,
 795,
 801,
 807,
 812,
 815,
 820,
 821,
 823,
 825,
 826,
 827,
 832,
 837,
 840,
 841,
 842,
 845,
 846,
 847,
 865,
 866,
 869,
 873,
 878,
 879,
 892,
 895,
 898,
 899,
 900,
 901,
 902,
 904,
 905,
 908,
 921,
 923,
 926,
 928,
 930,
 934,
 936,
 939,
 940,
 942,
 951,
 956,
 965,
 966,
 967,
 968,
 969,
 988,
 990,
 991,
 1020,
 1024,
 1028,
 1030,
 1033,
 1036,
 1037,
 1039,
 1041,
 1044,
 1047,
 1048,
 1050,
 1052,
 1053,
 1054,
 1061,
 1091,
 1092,
 1107,
 1112,
 1115,
 1116,
 1119,
 1126,
 1135,
 1140,
 1147,
 1152,
 1153,
 1160,
 1163,
 1172,
 1184,
 1192,
 1197,
 1203,
 1208,
 1212,
 1220,
 1221,
 1222,
 1226,
 1248,
 1249,
 1261,
 1263,
 1269,
 1271,
 1282,
 1284,
 1286,
 1297,
 1303,
 1311,
 1401,
 1402,
 1421,
 1425,
 1435,
 1441,
 1444,
 1446,
 1479,
 1480,
 1490,
 1518,
 1521,
 1603,
 1615]

In [34]:
# Cross Checking
sorted(user_input_watched_movie_list)

[242,
 245,
 259,
 286,
 288,
 289,
 292,
 294,
 299,
 310,
 312,
 324,
 329,
 332,
 690,
 898,
 899,
 990,
 991,
 1024]

In [35]:
# Checking the common movie list
list(set(unique_movieid_similar_user) & set(user_input_watched_movie_list))

[1024,
 898,
 259,
 899,
 286,
 288,
 289,
 292,
 294,
 299,
 690,
 310,
 312,
 324,
 329,
 332,
 990,
 991,
 242,
 245]

### Converting the user_prediction score values into Table

In [36]:
user_pred = pd.DataFrame(user_prediction)
user_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

### Taking transverse for making it easy to see the values in columns

In [37]:
user_pred_trans = user_pred.T
user_pred_trans

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.065326,1.763088,1.795904,1.729951,1.796651,1.996889,2.466055,1.693486,1.681165,2.021688,...,1.924844,1.619096,1.891812,1.696368,1.717658,1.676950,1.822346,1.591515,1.810363,1.838431
1,0.734303,0.384040,0.329047,0.293913,0.454474,0.651172,1.099186,0.296285,0.279528,0.650911,...,0.552456,0.311680,0.550513,0.322611,0.431368,0.346339,0.419125,0.275269,0.404799,0.479648
2,0.629924,0.196179,0.158829,0.127741,0.354422,0.528276,1.016489,0.195398,0.121887,0.530669,...,0.451194,0.140613,0.354913,0.144344,0.247851,0.177518,0.286430,0.102195,0.275450,0.384963
3,1.010669,0.731538,0.684154,0.644932,0.763130,0.921054,1.362861,0.612075,0.616094,0.916215,...,0.834176,0.661829,0.893214,0.662304,0.783208,0.689906,0.715605,0.624383,0.726616,0.780521
4,0.640686,0.225643,0.173277,0.142143,0.359539,0.537388,1.006458,0.198638,0.136368,0.531720,...,0.455212,0.166992,0.398759,0.167841,0.283796,0.199740,0.294442,0.133762,0.281316,0.388442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.392272,-0.089288,-0.137611,-0.163877,0.099951,0.259848,0.764340,-0.072866,-0.163505,0.263527,...,0.185602,-0.128949,0.095681,-0.143177,-0.009425,-0.094539,0.011978,-0.168486,-0.010138,0.145539
1678,0.394909,-0.087468,-0.136374,-0.162283,0.102515,0.262375,0.766967,-0.070435,-0.161425,0.266037,...,0.188059,-0.126624,0.097792,-0.141018,-0.007085,-0.092217,0.014065,-0.166217,-0.008009,0.148194
1679,0.393590,-0.088378,-0.136992,-0.163080,0.101233,0.261111,0.765654,-0.071651,-0.162465,0.264782,...,0.186831,-0.127786,0.096736,-0.142097,-0.008255,-0.093378,0.013021,-0.167352,-0.009074,0.146867
1680,0.393049,-0.086918,-0.134969,-0.161442,0.101075,0.261061,0.764983,-0.071744,-0.161396,0.264589,...,0.186850,-0.127045,0.097826,-0.140977,-0.007621,-0.092686,0.013639,-0.166575,-0.008466,0.146298
1681,0.392771,-0.086712,-0.134765,-0.161248,0.101201,0.261089,0.765165,-0.071357,-0.161430,0.264781,...,0.186858,-0.126812,0.097654,-0.140965,-0.007369,-0.092423,0.013796,-0.166414,-0.008049,0.146415

### Checking score values for user_input = 34

In [38]:
user_pred_trans[34]

0       1.740469
1       0.283366
2       0.114987
3       0.645096
4       0.127844
          ...
1677   -0.183977
1678   -0.182367
1679   -0.183172
1680   -0.181400
1681   -0.181306
Name: 34, Length: 1682, dtype: float64

In [39]:
user_pred_trans_df = pd.DataFrame(user_pred_trans)
user_pred_trans_df

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,2.065326,1.763088,1.795904,1.729951,1.796651,1.996889,2.466055,1.693486,1.681165,2.021688,...,1.924844,1.619096,1.891812,1.696368,1.717658,1.676950,1.822346,1.591515,1.810363,1.838431
1,0.734303,0.384040,0.329047,0.293913,0.454474,0.651172,1.099186,0.296285,0.279528,0.650911,...,0.552456,0.311680,0.550513,0.322611,0.431368,0.346339,0.419125,0.275269,0.404799,0.479648
2,0.629924,0.196179,0.158829,0.127741,0.354422,0.528276,1.016489,0.195398,0.121887,0.530669,...,0.451194,0.140613,0.354913,0.144344,0.247851,0.177518,0.286430,0.102195,0.275450,0.384963
3,1.010669,0.731538,0.684154,0.644932,0.763130,0.921054,1.362861,0.612075,0.616094,0.916215,...,0.834176,0.661829,0.893214,0.662304,0.783208,0.689906,0.715605,0.624383,0.726616,0.780521
4,0.640686,0.225643,0.173277,0.142143,0.359539,0.537388,1.006458,0.198638,0.136368,0.531720,...,0.455212,0.166992,0.398759,0.167841,0.283796,0.199740,0.294442,0.133762,0.281316,0.388442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.392272,-0.089288,-0.137611,-0.163877,0.099951,0.259848,0.764340,-0.072866,-0.163505,0.263527,...,0.185602,-0.128949,0.095681,-0.143177,-0.009425,-0.094539,0.011978,-0.168486,-0.010138,0.145539
1678,0.394909,-0.087468,-0.136374,-0.162283,0.102515,0.262375,0.766967,-0.070435,-0.161425,0.266037,...,0.188059,-0.126624,0.097792,-0.141018,-0.007085,-0.092217,0.014065,-0.166217,-0.008009,0.148194
1679,0.393590,-0.088378,-0.136992,-0.163080,0.101233,0.261111,0.765654,-0.071651,-0.162465,0.264782,...,0.186831,-0.127786,0.096736,-0.142097,-0.008255,-0.093378,0.013021,-0.167352,-0.009074,0.146867
1680,0.393049,-0.086918,-0.134969,-0.161442,0.101075,0.261061,0.764983,-0.071744,-0.161396,0.264589,...,0.186850,-0.127045,0.097826,-0.140977,-0.007621,-0.092686,0.013639,-0.166575,-0.008466,0.146298
1681,0.392771,-0.086712,-0.134765,-0.161248,0.101201,0.261089,0.765165,-0.071357,-0.161430,0.264781,...,0.186858,-0.126812,0.097654,-0.140965,-0.007369,-0.092423,0.013796,-0.166414,-0.008049,0.146415

In [40]:
user_pred_34 = user_pred_trans_df.T
user_pred_34

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,2.065326,0.734303,0.629924,1.010669,0.640686,0.476150,1.784569,1.163032,1.513350,0.704478,...,0.394041,0.394434,0.393981,0.392972,0.393344,0.392272,0.394909,0.393590,0.393049,0.392771
1,1.763088,0.384040,0.196179,0.731538,0.225643,0.003892,1.493597,0.876153,1.108467,0.261991,...,-0.086942,-0.085491,-0.087137,-0.088158,-0.087298,-0.089288,-0.087468,-0.088378,-0.086918,-0.086712
2,1.795904,0.329047,0.158829,0.684154,0.173277,-0.035621,1.488230,0.835769,1.135426,0.236383,...,-0.134795,-0.133537,-0.135543,-0.136438,-0.135041,-0.137611,-0.136374,-0.136992,-0.134969,-0.134765
3,1.729951,0.293913,0.127741,0.644932,0.142143,-0.062261,1.437010,0.796249,1.096663,0.211789,...,-0.161413,-0.160220,-0.161542,-0.162586,-0.161634,-0.163877,-0.162283,-0.163080,-0.161442,-0.161248
4,1.796651,0.454474,0.354422,0.763130,0.359539,0.195987,1.547370,0.908904,1.292027,0.437954,...,0.101762,0.102405,0.101923,0.100839,0.101711,0.099951,0.102515,0.101233,0.101075,0.101201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,1.676950,0.346339,0.177518,0.689906,0.199740,0.003297,1.429565,0.830905,1.070986,0.262183,...,-0.092434,-0.091197,-0.092851,-0.093801,-0.092953,-0.094539,-0.092217,-0.093378,-0.092686,-0.092423
939,1.822346,0.419125,0.286430,0.715605,0.294442,0.106633,1.514591,0.853050,1.195304,0.359260,...,0.014060,0.014688,0.014123,0.013060,0.013669,0.011978,0.014065,0.013021,0.013639,0.013796
940,1.591515,0.275269,0.102195,0.624383,0.133762,-0.069553,1.320734,0.765529,1.035088,0.192697,...,-0.166179,-0.164981,-0.166278,-0.167392,-0.166679,-0.168486,-0.166217,-0.167352,-0.166575,-0.166414
941,1.810363,0.404799,0.275450,0.726616,0.281316,0.087068,1.550310,0.850057,1.205745,0.342987,...,-0.008362,-0.007757,-0.008225,-0.009218,-0.008232,-0.010138,-0.008009,-0.009074,-0.008466,-0.008049
942,1.838431,0.479648,0.384963,0.780521,0.388442,0.240998,1.564232,0.946704,1.289865,0.487383,...,0.147027,0.148208,0.147193,0.146199,0.146916,0.145539,0.148194,0.146867,0.146298,0.146415

### Cheking the rating for random movie

In [41]:
user_pred_34[187].values

array([0.9054316 , 0.61609128, 0.55617678, 0.51707383, 0.65536913,
       0.80121348, 1.24729706, 0.47915807, 0.49127658, 0.80565586,
       0.74785664, 0.50659897, 1.50188464, 0.6243933 , 0.64776116,
       0.69250443, 0.50376818, 0.97557595, 0.47280153, 0.48421414,
       0.7159752 , 0.59534733, 0.66690457, 0.56524345, 0.56464289,
       0.65286149, 0.49434383, 0.54988414, 0.52107123, 0.53171071,
       0.51349536, 0.52839319, 0.53006367, 0.51344346, 0.51622969,
       0.50562094, 0.48441144, 0.66280025, 0.53119256, 0.5404285 ,
       0.47710974, 0.74377421, 0.8616363 , 0.66227257, 0.54537031,
       0.53364794, 0.53262804, 0.52917666, 0.72621474, 0.50090784,
       0.44084076, 0.57564642, 0.48146654, 0.59978409, 0.44352688,
       0.73577975, 0.64182581, 0.71879427, 1.19016778, 0.83909318,
       0.51661747, 0.78623431, 0.63795203, 0.73122374, 0.56489787,
       0.5290225 , 0.49722113, 0.51474134, 0.56635729, 0.6203387 ,
       0.49137939, 0.63767748, 0.51479267, 0.56116699, 0.58148793,
       0.56686115, 0.49937977, 0.50302679, 0.59456966, 0.47606221,
       0.5404285 , 0.67361409, 0.69755843, 0.57930316, 0.93835243,
       0.52158036, 0.80010571, 0.51710395, 0.61220276, 1.1166686 ,
       0.58726839, 1.06557657, 0.48945263, 1.16927951, 0.87726173,
       0.4939911 , 0.50540462, 0.47249679, 0.68775406, 0.59308333,
       0.55743517, 0.68201984, 0.48153217, 0.64760975, 0.52901261,
       0.53999588, 0.51548707, 0.51652834, 0.80387987, 0.62023378,
       0.53416165, 0.59095768, 0.58449706, 0.46142388, 0.58281623,
       0.69785163, 0.59704034, 0.56069831, 0.82143843, 0.50638172,
       0.5757183 , 0.53873035, 0.53213316, 0.42997232, 0.73465833,
       0.57562406, 0.49856999, 0.76309579, 0.53064375, 1.19209006,
       0.53839314, 0.47451564, 0.52751193, 0.53501788, 0.50020773,
       0.53301025, 0.52786335, 0.52143392, 0.5112084 , 0.5244494 ,
       0.67953925, 0.49193209, 0.52467001, 0.81952381, 1.00208722,
       0.53943764, 0.52726956, 0.52982817, 0.54821239, 0.51285798,
       1.06787181, 0.67898011, 0.44200201, 0.5068482 , 0.51443042,
       0.47207866, 0.56660312, 0.73028858, 0.67042745, 0.66328021,
       0.48431731, 0.49895113, 0.47656842, 0.61512769, 0.48897525,
       0.5185579 , 0.54332593, 0.59286534, 0.50526721, 0.52446989,
       0.53868619, 0.46575274, 0.59557767, 0.78542479, 0.45869343,
       0.59663457, 0.59799349, 0.93829434, 0.55283556, 0.5302997 ,
       0.85218375, 0.4857929 , 0.49141325, 0.90940847, 0.54192254,
       0.6045276 , 0.5184156 , 0.59901764, 0.80503537, 0.58399468,
       0.53555004, 0.52687277, 0.64033955, 0.82934706, 0.60579631,
       0.51566077, 0.60210646, 0.65493552, 0.53551856, 0.85639053,
       1.02249576, 0.45219028, 0.54242931, 0.54230744, 0.52349993,
       0.56225415, 0.78111618, 0.47604401, 0.51581444, 0.65317398,
       0.49071204, 0.4720647 , 0.66377396, 0.65363675, 0.54387568,
       0.64029298, 0.49988967, 0.4943725 , 0.48843394, 0.53502705,
       0.68006501, 1.01490256, 0.62681088, 0.66601611, 0.48079018,
       0.51154042, 0.56910602, 0.48426919, 0.52614732, 0.64753474,
       0.49984705, 0.59774326, 0.64372675, 1.22209969, 0.59400981,
       0.63401938, 0.4942056 , 0.51871554, 0.76676894, 0.53792612,
       0.52851343, 0.50814953, 0.58493924, 0.86541153, 0.48497244,
       0.69398395, 0.50241027, 0.48745136, 0.73332159, 0.65999688,
       0.5847141 , 0.50891818, 0.58853799, 0.64675441, 0.55392118,
       0.86053577, 0.59048446, 0.53702144, 0.51400321, 0.52471552,
       0.53229744, 0.67351212, 0.63889715, 0.6762807 , 0.55730123,
       0.5127942 , 0.7382976 , 0.88717106, 0.91330962, 0.76142779,
       0.922552  , 0.48460327, 0.51841668, 0.60707371, 0.53477346,
       1.37743217, 0.56358542, 0.51587321, 1.20088767, 0.90180382,
       0.52916429, 0.52190087, 0.52374714, 0.58780063, 0.51328206,
       1.00571633, 0.57154052, 0.55904437, 0.48084563, 0.63625479,
       0.99430452, 0.67393904, 1.00004555, 0.76492584, 0.82717796,
       0.75646761, 0.75240909, 0.65304425, 0.94001783, 0.50358656,
       0.88587769, 0.5010974 , 1.2884314 , 0.52546282, 0.79936504,
       0.5379392 , 0.60391285, 1.19081824, 0.51317952, 0.50211819,
       0.96891565, 0.93217268, 0.86748904, 0.93392223, 0.58359355,
       0.54613747, 0.51687652, 0.75516255, 0.51788719, 0.69491942,
       0.65058277, 0.51081673, 0.5951147 , 0.64536899, 0.64519284,
       0.68378212, 0.88651612, 0.90808605, 0.55884597, 0.7495533 ,
       0.5615568 , 0.8296439 , 0.47956466, 1.05644111, 0.52455953,
       0.62895741, 0.49637283, 0.5708933 , 0.91245061, 0.50096647,
       0.50453126, 0.78364338, 0.88849157, 0.79496996, 0.88635365,
       0.69711035, 0.75794345, 0.58576953, 0.52323658, 0.50023589,
       0.59282249, 0.44710342, 0.53052009, 0.90672301, 0.52976875,
       0.5337919 , 0.63549686, 0.5170459 , 0.510197  , 0.63623283,
       0.65097681, 0.53034593, 0.89066552, 0.51547537, 0.58139023,
       0.49815669, 0.55468842, 0.49391728, 0.48122269, 0.54857405,
       0.47715219, 0.5861612 , 0.8445093 , 0.88067882, 0.47547819,
       0.50038105, 0.51152029, 1.10141162, 0.77926011, 0.65530813,
       0.68252969, 0.51279291, 0.57611386, 0.53210487, 0.9063811 ,
       0.47893306, 0.91452474, 0.58516051, 0.94388265, 0.54116931,
       0.62172867, 0.69306845, 1.25422424, 0.6713391 , 0.5426788 ,
       0.56077098, 0.60627935, 0.70743903, 0.89001536, 0.53737527,
       0.65708489, 0.57016625, 0.55007772, 0.56592438, 1.11935178,
       1.03225085, 0.77697603, 0.54131361, 0.79331591, 0.53049199,
       0.48903581, 0.48941782, 0.58315223, 0.5247551 , 0.47330296,
       1.47591949, 1.02175543, 0.51222278, 0.5031185 , 0.53659522,
       0.50641441, 0.63405559, 0.61347904, 0.55321744, 0.71102845,
       0.6066076 , 0.55415293, 0.61594897, 1.13096187, 0.56250151,
       0.52667773, 0.58982079, 0.52861174, 0.54467149, 1.05631993,
       0.70003206, 0.90220551, 0.53932364, 0.52125816, 0.58266526,
       0.49940649, 0.60298551, 0.51730823, 0.52470352, 0.56560592,
       0.54530432, 0.66455001, 0.54684098, 0.60457102, 1.56549485,
       0.64575105, 0.75035667, 0.64770301, 0.7701892 , 0.75951672,
       0.78432299, 0.97251234, 0.77407527, 0.67217899, 0.6037254 ,
       0.51175661, 0.54003642, 0.69244725, 0.58627527, 0.54442149,
       0.58432696, 0.53958264, 0.69360898, 0.52093378, 0.57242214,
       0.4830096 , 1.00047515, 0.53202095, 1.10605274, 0.49939812,
       0.55787672, 0.53548858, 0.59533871, 0.74032804, 0.51978359,
       0.52603301, 0.53039068, 0.52406215, 0.66935326, 0.52565637,
       0.8261782 , 0.83567254, 0.64992188, 0.7288355 , 0.5352352 ,
       0.50972117, 0.50645659, 0.64919757, 0.52210513, 0.81667367,
       0.59341348, 0.85113059, 0.64937827, 0.61973131, 0.83395071,
       0.60385689, 0.53982243, 0.75707893, 0.90369574, 0.59082816,
       0.84710881, 0.63451277, 0.53044285, 0.51891002, 0.53589318,
       0.52304989, 0.46531845, 0.48258123, 0.7676488 , 0.55896995,
       0.47006619, 0.52830193, 0.59996639, 0.57833636, 0.52387466,
       0.60003439, 0.45990454, 0.67021769, 0.96651691, 0.55859065,
       0.59975491, 0.64963151, 0.50665192, 0.57955875, 0.50296506,
       0.53427628, 1.03966508, 0.86800187, 0.64032514, 0.85944922,
       0.70976236, 1.16553952, 0.49613884, 0.54909231, 0.59618052,
       0.67381618, 0.62658827, 0.73876271, 0.5400173 , 0.66341576,
       0.5684717 , 0.52747356, 0.75949132, 0.50044864, 0.55933001,
       1.07659469, 0.61255089, 0.61563989, 0.61626487, 0.55550922,
       0.52071463, 0.55665078, 0.50802386, 0.52106414, 0.61340075,
       0.94981563, 0.52556595, 0.49357335, 0.52965142, 0.51962939,
       0.65052533, 0.71820463, 0.56595079, 0.60890724, 0.51054292,
       0.4475956 , 0.49880909, 0.50064479, 0.57976767, 0.43960947,
       0.5079678 , 0.75847234, 0.50297199, 0.54793495, 0.55581733,
       0.50819478, 0.5735351 , 0.47659789, 0.46581705, 0.61328835,
       0.66318945, 0.66448293, 0.87212657, 0.57498478, 0.55252028,
       0.57532111, 1.17364659, 0.70916358, 0.49673666, 0.62821995,
       0.51976857, 0.54973311, 0.5258307 , 0.5642078 , 0.52565597,
       0.62521301, 0.52090694, 0.49691649, 0.46669349, 0.60404616,
       0.87943738, 0.49625751, 0.73362546, 0.50273587, 0.54744963,
       0.57419173, 0.50254221, 0.48511752, 0.52182339, 0.62428428,
       0.58247481, 0.56648936, 0.73891398, 0.56198366, 0.67141451,
       0.73783888, 0.78815353, 0.49769154, 0.76765472, 0.56922055,
       0.52558619, 0.67567984, 0.54510985, 0.66351449, 0.62911393,
       0.51255801, 0.57153352, 0.50128927, 0.73363903, 0.53942287,
       0.5068324 , 0.61502252, 0.47400576, 0.65614008, 0.63715518,
       0.51199355, 1.05914937, 0.77127272, 0.56254926, 0.6210971 ,
       0.54870077, 0.52890956, 0.89600036, 0.49421018, 0.88647342,
       0.51036932, 0.50782073, 0.76069522, 0.70214994, 1.54277153,
       0.50540161, 0.52012718, 0.54103584, 0.76003623, 0.67652098,
       0.62778268, 0.50163487, 0.73494623, 0.70355525, 0.66409336,
       0.86007054, 0.51060429, 0.55595656, 0.58250215, 0.49301082,
       0.61438185, 0.50697787, 0.55819277, 0.54758805, 0.52661988,
       0.59729286, 0.56048467, 0.50503794, 0.52056416, 0.5267659 ,
       0.5140174 , 1.05568963, 0.60139911, 0.56891572, 0.49012044,
       0.53428735, 0.52596031, 0.52949661, 0.53129278, 0.57614526,
       0.48749753, 0.50957419, 0.62464863, 0.70786311, 0.54739513,
       0.52062254, 0.6946724 , 0.58087271, 0.72617985, 0.42967303,
       0.56017786, 0.49149626, 0.55498972, 0.590197  , 0.6196209 ,
       0.51007239, 0.89616892, 0.66656847, 0.62855387, 0.56932605,
       0.87267783, 0.73731507, 0.52475878, 0.54236203, 0.66566881,
       0.93962108, 0.67521101, 0.53578597, 0.51750805, 0.54568368,
       0.75439496, 0.54880164, 0.46319923, 0.60286755, 0.5352199 ,
       0.49471508, 0.89569202, 0.51647593, 0.50878721, 0.53681488,
       0.55106141, 0.52485856, 0.64613664, 0.5311773 , 0.57824166,
       0.4918101 , 0.45664515, 0.62753636, 0.471567  , 0.53056178,
       0.57559401, 0.49842797, 0.55409435, 0.47357004, 0.49453984,
       0.4810852 , 1.0399497 , 0.57012751, 0.96700733, 0.54675622,
       0.71749058, 0.62032094, 0.51461832, 0.52155632, 0.5603537 ,
       0.58889393, 0.65923551, 1.17121762, 0.53780492, 0.50532044,
       0.5614799 , 0.48440415, 0.65446923, 0.63161951, 0.50391383,
       0.66720404, 0.49921014, 0.58419973, 0.50042382, 0.62801238,
       0.57571705, 0.56446386, 0.66695652, 0.58109221, 0.54353192,
       0.57513392, 0.48715374, 0.47290449, 0.53184211, 0.50482053,
       0.47613241, 0.8629452 , 0.54400844, 0.5784976 , 0.461602  ,
       0.60468399, 0.59326316, 0.82017974, 0.51429471, 0.76246753,
       0.53951478, 0.52680638, 0.5518395 , 0.53913072, 0.64406575,
       1.093651  , 0.49846538, 0.86643761, 0.49823183, 0.51759583,
       0.54103903, 0.57877987, 0.53968491, 1.02200411, 0.88878789,
       0.63504576, 0.81952145, 0.53629177, 0.52483522, 0.55319169,
       0.53182989, 0.52138127, 0.51434689, 0.47395517, 0.72995368,
       0.53280339, 0.52527756, 0.52431318, 0.52524927, 0.51525349,
       0.5598102 , 0.47854446, 0.74591292, 0.50427962, 0.74041296,
       0.6057433 , 0.54524766, 0.64031246, 0.57152192, 0.57917861,
       0.57302688, 0.52203108, 0.80931477, 0.59665343, 0.62405385,
       0.51945183, 0.54650843, 0.61742564, 0.55900231, 0.81699343,
       0.55290895, 0.53076155, 0.64864632, 0.5383523 , 0.52733099,
       1.19473923, 0.62760108, 0.72293776, 0.48424299, 0.50881806,
       0.82996177, 0.53346344, 0.55836985, 0.78097177, 0.47299654,
       0.53957173, 0.50875221, 0.50266303, 0.53822144, 0.58467825,
       0.54958414, 0.75236664, 0.68959839, 0.97915282, 0.52823478,
       0.4992555 , 0.58398056, 0.6873223 , 0.5324995 , 0.87301842,
       0.64515919, 0.60371413, 0.51668584, 0.52151699, 0.59627079,
       0.47227537, 0.59825187, 0.64724539, 0.5132602 , 1.08882666,
       0.82465139, 0.6706164 , 0.99160727, 0.53171768, 0.56892387,
       0.78424305, 0.78123884, 0.48281392, 0.97555054, 0.61726907,
       0.56854112, 0.84416102, 0.54311746, 0.98465607, 0.49849393,
       0.94154435, 0.75252606, 0.53716057, 0.61387265, 0.48722193,
       0.65126521, 0.51709914, 0.65949658, 0.54241433, 0.54605576,
       0.54571867, 0.82299006, 0.52214344, 0.52471038, 0.53119703,
       0.58127939, 0.49742905, 0.61215503, 0.4727794 , 0.52868619,
       0.93752622, 0.5239857 , 0.60419253, 0.87942494, 0.53305481,
       0.61852725, 0.60763906, 0.62100274, 0.56547196, 0.497522  ,
       0.52896621, 0.65692807, 0.51088991, 0.45690599, 0.54674976,
       0.60969581, 0.90290322, 0.58738097, 0.73391662, 0.54536818,
       0.77643903, 0.54431153, 0.66655832, 0.57397928, 0.61216146,
       0.4996893 , 0.60267881, 0.66729907])

In [42]:
user_pred_34[187].values > 0.4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

## Step 10&11 - With the help of 'Threshold values' we can select the highest-rated movies list 
### From the recommended list select the highest rated film that would like by the user. Based on User prediction

In [43]:
highest_rated = []
user_input_pred = pd.DataFrame(user_pred_trans[user_input])
user_input_pred = user_input_pred.T
for movie in recommended_movie_list:
    value = user_input_pred[movie].values
    if (value >= 1):
        highest_rated.append(movie)

In [44]:
user_input_pred

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
34,1.740469,0.283366,0.114987,0.645096,0.127844,-0.081329,1.448638,0.794313,1.08901,0.194232,...,-0.181256,-0.180156,-0.181837,-0.182819,-0.181432,-0.183977,-0.182367,-0.183172,-0.1814,-0.181306

In [45]:
len(highest_rated)

27

In [46]:
highest_rated

[11,
 49,
 63,
 78,
 88,
 95,
 97,
 99,
 126,
 167,
 172,
 173,
 180,
 182,
 190,
 194,
 203,
 215,
 221,
 257,
 268,
 275,
 287,
 301,
 356,
 422,
 482]

### Getting Movies list for respective Movie ids

In [47]:
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('C:\Priya learning path\Hope_Artifiacial_Intelligence\Recommendation system\Collabrative Recommendation System\ml-100k/u.item',
                    sep='|', names=i_cols,encoding='latin-1')

In [48]:
items

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Creating Movie Title List based on recommended movie_id

In [49]:
movie_title = []
for movieid in highest_rated:
    mov = items[items['movie id']==movieid]['movie title'].values
    movie_title.append(mov)

In [50]:
movie_title

[array(['Seven (Se7en) (1995)'], dtype=object),
 array(['I.Q. (1994)'], dtype=object),
 array(['Santa Clause, The (1994)'], dtype=object),
 array(['Free Willy (1993)'], dtype=object),
 array(['Sleepless in Seattle (1993)'], dtype=object),
 array(['Aladdin (1992)'], dtype=object),
 array(['Dances with Wolves (1990)'], dtype=object),
 array(['Snow White and the Seven Dwarfs (1937)'], dtype=object),
 array(['Spitfire Grill, The (1996)'], dtype=object),
 array(['Private Benjamin (1980)'], dtype=object),
 array(['Empire Strikes Back, The (1980)'], dtype=object),
 array(['Princess Bride, The (1987)'], dtype=object),
 array(['Apocalypse Now (1979)'], dtype=object),
 array(['GoodFellas (1990)'], dtype=object),
 array(['Henry V (1989)'], dtype=object),
 array(['Sting, The (1973)'], dtype=object),
 array(['Unforgiven (1992)'], dtype=object),
 array(['Field of Dreams (1989)'], dtype=object),
 array(['Breaking the Waves (1996)'], dtype=object),
 array(['Men in Black (1997)'], dtype=object),
 array(['Chasing Amy (1997)'], dtype=object),
 array(['Sense and Sensibility (1995)'], dtype=object),
 array(["Marvin's Room (1996)"], dtype=object),
 array(['In & Out (1997)'], dtype=object),
 array(['Client, The (1994)'], dtype=object),
 array(['Aladdin and the King of Thieves (1996)'], dtype=object),
 array(['Some Like It Hot (1959)'], dtype=object)]

### Converting into pure list

In [51]:
movie_title_list = []
for title in movie_title:
    mv = list(title)
    movie_title_list.append(mv)

In [52]:
movie_title_list

[['Seven (Se7en) (1995)'],
 ['I.Q. (1994)'],
 ['Santa Clause, The (1994)'],
 ['Free Willy (1993)'],
 ['Sleepless in Seattle (1993)'],
 ['Aladdin (1992)'],
 ['Dances with Wolves (1990)'],
 ['Snow White and the Seven Dwarfs (1937)'],
 ['Spitfire Grill, The (1996)'],
 ['Private Benjamin (1980)'],
 ['Empire Strikes Back, The (1980)'],
 ['Princess Bride, The (1987)'],
 ['Apocalypse Now (1979)'],
 ['GoodFellas (1990)'],
 ['Henry V (1989)'],
 ['Sting, The (1973)'],
 ['Unforgiven (1992)'],
 ['Field of Dreams (1989)'],
 ['Breaking the Waves (1996)'],
 ['Men in Black (1997)'],
 ['Chasing Amy (1997)'],
 ['Sense and Sensibility (1995)'],
 ["Marvin's Room (1996)"],
 ['In & Out (1997)'],
 ['Client, The (1994)'],
 ['Aladdin and the King of Thieves (1996)'],
 ['Some Like It Hot (1959)']]

In [53]:
final_recommenmded_movie_list = list(itertools.chain.from_iterable(movie_title_list))

In [54]:
final_recommenmded_movie_list

['Seven (Se7en) (1995)',
 'I.Q. (1994)',
 'Santa Clause, The (1994)',
 'Free Willy (1993)',
 'Sleepless in Seattle (1993)',
 'Aladdin (1992)',
 'Dances with Wolves (1990)',
 'Snow White and the Seven Dwarfs (1937)',
 'Spitfire Grill, The (1996)',
 'Private Benjamin (1980)',
 'Empire Strikes Back, The (1980)',
 'Princess Bride, The (1987)',
 'Apocalypse Now (1979)',
 'GoodFellas (1990)',
 'Henry V (1989)',
 'Sting, The (1973)',
 'Unforgiven (1992)',
 'Field of Dreams (1989)',
 'Breaking the Waves (1996)',
 'Men in Black (1997)',
 'Chasing Amy (1997)',
 'Sense and Sensibility (1995)',
 "Marvin's Room (1996)",
 'In & Out (1997)',
 'Client, The (1994)',
 'Aladdin and the King of Thieves (1996)',
 'Some Like It Hot (1959)']

### Checking the common movies list

In [55]:
list(set(recommended_movie_list) & (set(user_input_watched_movie_list)))

[]

So, Algorithm is Correct

### Compiled all the steps in single function

In [56]:
def userbased(user_input,user_similarity,user_prediction,similar_user_count,threshold):
    #Convert the user_sim table into DataFrame
    user_sim_table=pd.DataFrame(user_similarity)
    #Find similarity user for 34 using cosine table
    similar_user_input = user_sim_table[user_input].sort_values(ascending=True).head(similar_user_count).index
    #Convert into list
    similar_user_input=list(similar_user_input) 
    #Using similar_user_input,can select movie id from ratings table
    similar_user_movieid_list=[]
    for sim_user in similar_user_input:
        sim=list(ratings[ratings['user_id']==sim_user]['movie_id'])
        similar_user_movieid_list.append(sim)
    #Converting as a whole list
    import itertools
    similar_user_movieid_single_list=list(itertools.chain.from_iterable(similar_user_movieid_list))
    #Unique movieid from the list
    Unique_movieid_similar_user=set(similar_user_movieid_single_list)
    #Input user watched movie_list
    user_input_watched_movieid=list(ratings[ratings['user_id']==user_input]['movie_id'].values)
    #Create a list which should have recom movieid to the input user
    recommended_movie_list=[]
    for per_id in Unique_movieid_similar_user:
        if(per_id in user_input_watched_movieid):
            pass
        else:
            recommended_movie_list.append(per_id)
    #From recommendation list selecting only hightest rated(predicted) value
    highest_rated=[]
    user_pred = pd.DataFrame(user_prediction)
    user_pred_trans = user_pred.T
    user_input_pred = pd.DataFrame(user_pred_trans[user_input])
    user_input_pred = user_input_pred.T
    for movie in recommended_movie_list:
        value=user_input_pred[movie].values
        if(value>=threshold):
            highest_rated.append(movie)
    #Getting Movies list for respective Movie ids
    i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
    items = pd.read_csv('C:\Priya learning path\Hope_Artifiacial_Intelligence\Recommendation system\Collabrative Recommendation System\ml-100k/u.item',
                         sep='|', names=i_cols,encoding='latin-1')
    #Creating Movie List based on recommended movieid
    movie_title=[]
    for movieid in highest_rated:
        mov=items[items['movie id']==movieid]['movie title'].values
        movie_title.append(mov)
    #Converting into pure list
    movie_title_list=[]
    for title in movie_title:
        mv=list(title)
        movie_title_list.append(mv)
    #Converting into whole list
    import itertools
    final_recommenmded_movie_list = list(itertools.chain.from_iterable(movie_title_list))
    print("The common Movie in Recommended list & User:",list(set(recommended_movie_list) & (set(user_input_watched_movieid))))
    return final_recommenmded_movie_list

In [57]:
#def userbased(input_user,user_similarity,user_predictions,similar_user_count,threshold)

Recommended_movie_list = userbased(65, user_similarity, user_pred, 5,1.5)

The common Movie in Recommended list & User: []

In [58]:
Recommended_movie_list

['Snow White and the Seven Dwarfs (1937)',
 'Delicatessen (1991)',
 'Men in Black (1997)',
 'Secrets & Lies (1996)',
 "Marvin's Room (1996)"]

In [59]:
len(Recommended_movie_list)

5